#!/usr/bin/env bash
#
# Runs the Jekyll toolchain inside a container whose Ruby matches the one the
# deployment workflow uses.
#
# Why this script exists: Gemfile.lock is generated by Bundler 2.5.23 and pins
# nokogiri 1.18.x, which requires Ruby >= 3.1. A machine whose system Ruby is
# older than that cannot install this bundle at all, and older Bundler releases
# additionally mismatch the linux-gnu / linux-musl platform variants recorded in
# the lockfile. Rather than replacing the system Ruby, every Jekyll command runs
# in the same image the deployment workflow pins.
#
# RUBY_IMAGE below must stay in sync with the ruby-version in
# .github/workflows/deploy.yml.

set -euo pipefail

RUBY_IMAGE="ruby:3.3.5"
DEFAULT_PORT=4000
LIVERELOAD_PORT=35729

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
  cat <<'EOF'
Usage: tools/jekyll-docker.sh <command> [arguments]

  install         Install the gems recorded in Gemfile.lock into vendor/bundle
  check           Report whether the installed gems satisfy Gemfile.lock
  build           Build the site into _site/
  serve [port]    Serve the site with live reload (default port 4000)
  shell           Open an interactive shell inside the container
  run <command>   Run an arbitrary command inside the container

Gems are installed into vendor/bundle, which Git ignores and the Jekyll build
excludes, so they survive between runs and are downloaded only once.

build and serve install the gems first if they are missing, so a clean checkout
needs no separate install step.
EOF
}

# Succeeds when something is already listening on the given port of the
# loopback interface. Docker reports a port clash only after pulling the whole
# command apart, so checking up front produces a far clearer message.
port_in_use() {
  (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null || return 1
  exec 3>&-
  return 0
}

require_free_port() {
  if port_in_use "$1"; then
    echo "Port $1 on 127.0.0.1 is already taken by another process." >&2
    echo "Pass a free port instead, for example: tools/jekyll-docker.sh serve 4001" >&2
    exit 1
  fi
}

require_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    echo "docker was not found on PATH." >&2
    exit 1
  fi
  if ! docker info >/dev/null 2>&1; then
    echo "Cannot reach the Docker daemon. Check that it is running and that your user is in the docker group." >&2
    exit 1
  fi
}

# Runs its arguments as a command inside the container, with the repository bind
# mounted at /srv. PUBLISH_PORTS, if non-empty, is forwarded as --publish flags.
run_in_container() {
  local -a docker_args=(
    --rm
    --user "$(id -u):$(id -g)"
    --volume "${REPO_ROOT}:/srv"
    --workdir /srv
    --env HOME=/tmp
    --env BUNDLE_APP_CONFIG=/srv/.bundle
    --env BUNDLE_PATH=/srv/vendor/bundle
  )

  if [ -t 0 ] && [ -t 1 ]; then
    docker_args+=(--interactive --tty)
  fi

  local port
  for port in "${PUBLISH_PORTS[@]}"; do
    docker_args+=(--publish "${port}")
  done

  docker run "${docker_args[@]}" "${RUBY_IMAGE}" "$@"
}

# Runs a shell snippet inside the container, installing the gems first if they
# are missing. Both steps share a single container so the common case where the
# gems are already present costs one container start, not two.
run_with_gems() {
  run_in_container bash -c 'bundle check >/dev/null 2>&1 || bundle install --jobs "$(nproc)"
'"$1"
}

# Jekyll's --config takes a comma separated list, and it fails outright when a
# listed file is missing. _config.local.yml is a personal, Git ignored override
# that may or may not be present, so it is appended only when it exists.
config_list() {
  if [ -f "${REPO_ROOT}/_config.local.yml" ]; then
    echo "_config.yml,_config.local.yml"
  else
    echo "_config.yml"
  fi
}

main() {
  local command="${1:-}"
  shift || true

  PUBLISH_PORTS=()

  case "${command}" in
    install)
      require_docker
      run_in_container bash -c 'bundle install --jobs "$(nproc)"'
      ;;
    check)
      require_docker
      run_in_container bundle check
      ;;
    build)
      require_docker
      run_with_gems "bundle exec jekyll build --config $(config_list) --disable-disk-cache"
      ;;
    serve)
      require_docker
      local port="${1:-${DEFAULT_PORT}}"
      require_free_port "${port}"
      require_free_port "${LIVERELOAD_PORT}"
      PUBLISH_PORTS=("127.0.0.1:${port}:${port}" "127.0.0.1:${LIVERELOAD_PORT}:${LIVERELOAD_PORT}")
      echo "Serving on http://127.0.0.1:${port}/ - press Ctrl+C to stop."
      run_with_gems "bundle exec jekyll serve --host 0.0.0.0 --port ${port} --livereload --livereload-port ${LIVERELOAD_PORT} --config $(config_list) --disable-disk-cache"
      ;;
    shell)
      require_docker
      run_in_container bash
      ;;
    run)
      if [ "$#" -eq 0 ]; then
        echo "run needs a command to execute." >&2
        exit 1
      fi
      require_docker
      run_in_container "$@"
      ;;
    -h | --help | help | "")
      usage
      ;;
    *)
      echo "Unknown command: ${command}" >&2
      echo >&2
      usage >&2
      exit 1
      ;;
  esac
}

main "$@"
